apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment2
  labels:
    app: payment2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment2
  template:
    metadata:
      labels:
        app: payment2
    spec:
      containers:
        - name: payment2
          image: username/payment2:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5